WebServer:
  package:
    mysql-server:
    php5-mysql:
    php5-sqlite:
    sqlite3:
    apache2:
    git:
  password_mysql: 	aragorn
  VirtualizeMe:
    url:		http://192.168.202.120/VirtualizeMe
    git:		https://github.com/bernard-c/VirtualizeMe.git